import type { Product } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: 'foif-a90',
    name: 'FOIF A90',
    brand: 'FOIF',
    slug: 'foif-a90',
    description: 'Récepteur GNSS RTK haute précision pour levés topographiques professionnels.',
    longDescription:
      'Le FOIF A90 est un récepteur GNSS multi-constellation de dernière génération, offrant une précision centimétrique en temps réel. Idéal pour les levés topographiques, l\'implantation et les contrôles géodésiques en milieu urbain et rural.',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo, QZSS',
      'Canaux': '756 canaux',
      'Précision RTK': '±8mm + 1ppm (H), ±15mm + 1ppm (V)',
      'Précision statique': '±2.5mm + 0.1ppm (H)',
      'Temps d\'initialisation': '< 10 secondes',
      'Autonomie': '10 heures (batterie interne)',
      'Protection': 'IP67',
      'Bluetooth': 'BT 4.0',
      'Communication': '4G LTE intégré',
      'Poids': '1.1 kg',
    },
    applications: [
      'Levés topographiques',
      'Implantation de chantier',
      'Contrôles géodésiques',
      'Cartographie de précision',
      'Suivi de déformations',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: true,
  },
  {
    id: 'sunnav-s100',
    name: 'SUNNAV S100',
    brand: 'SUNNAV',
    slug: 'sunnav-s100',
    description: 'Récepteur GNSS compact et robuste, conçu pour les conditions de terrain exigeantes.',
    longDescription:
      'Le SUNNAV S100 combine légèreté et haute performance pour les professionnels de la topographie. Sa robustesse IP68 et sa longue autonomie en font un outil de référence pour les missions de terrain intensives.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo',
      'Canaux': '672 canaux',
      'Précision RTK': '±10mm + 1ppm (H), ±20mm + 1ppm (V)',
      'Autonomie': '12 heures',
      'Protection': 'IP68',
      'Écran': 'LCD rétroéclairé',
      'Mémoire interne': '8 Go',
      'Poids': '0.95 kg',
    },
    applications: [
      'Levés de terrain',
      'Topographie routière',
      'Bornage foncier',
      'Cartographie SIG',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: true,
  },
  {
    id: 'hi-target-v200',
    name: 'HI-TARGET V200',
    brand: 'HI-TARGET',
    slug: 'hi-target-v200',
    description: 'Récepteur GNSS RTK robuste de la gamme V-Series pour tous types de levés.',
    longDescription:
      'Le HI-TARGET V200 est issu de la gamme V-Series réputée pour sa fiabilité. Il offre des performances RTK de premier ordre avec une technologie de compensation d\'inclinaison intégrée, permettant les mesures en mode incliné sans trépied.',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80',
    specifications: {
      'Constellations': 'GPS L1/L2, GLONASS L1/L2, BeiDou B1/B2/B3, Galileo E1/E5a',
      'Précision RTK': '±8mm + 1ppm (H)',
      'IMU intégrée': 'Oui – compensation jusqu\'à 60°',
      'Autonomie': '9 heures',
      'Protection': 'IP67',
      '4G/WiFi': 'Oui',
      'Poids': '1.25 kg',
    },
    applications: [
      'Topographie de précision',
      'Levés en zones difficiles d\'accès',
      'Bornage cadastral',
      'Infrastructure et BTP',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: false,
  },
  {
    id: 'hi-target-v300',
    name: 'HI-TARGET V300',
    brand: 'HI-TARGET',
    slug: 'hi-target-v300',
    description: 'Solution GNSS RTK avancée avec compensation d\'inclinaison et connectivité étendue.',
    longDescription:
      'Le HI-TARGET V300 représente une évolution significative dans la gamme V-Series. Il intègre une technologie IMU de compensation d\'inclinaison jusqu\'à 60° et offre une connectivité 4G/WiFi pour le travail en réseau RTK.',
    image: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo, QZSS, SBAS',
      'Canaux': '1408 canaux',
      'Précision RTK': '±8mm + 1ppm (H), ±15mm + 1ppm (V)',
      'IMU': 'Compensation d\'inclinaison ±60°',
      'Autonomie': '10 heures',
      'Protection': 'IP67',
      'Poids': '1.3 kg',
    },
    applications: [
      'Levés topographiques complexes',
      'Suivi de chantier BTP',
      'Études routières',
      'Cartographie aéroportuaire',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: false,
    featured: false,
  },
  {
    id: 'hi-target-v600',
    name: 'HI-TARGET V600',
    brand: 'HI-TARGET',
    slug: 'hi-target-v600',
    description: 'Le fleuron de la gamme HI-TARGET — récepteur GNSS professionnel haute performance.',
    longDescription:
      'Le HI-TARGET V600 est le récepteur GNSS le plus avancé de la gamme V-Series. Il embarque une antenne GNSS à pleine bande, une technologie de compensation d\'inclinaison IMU de précision, et une connectivité tout-en-un pour répondre aux exigences les plus strictes.',
    image: 'https://images.unsplash.com/photo-1581092334247-ddef2a41a625?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo, QZSS, NavIC',
      'Canaux': '1408 canaux (pleine bande)',
      'Précision RTK': '±5mm + 0.5ppm (H)',
      'IMU': 'Compensation ±60°, précision ±2.5cm à 60°',
      'Autonomie': '10h (interne) + batterie externe',
      'Protection': 'IP67',
      '4G/WiFi/BT': 'Triple connectivité',
      'Poids': '1.35 kg',
    },
    applications: [
      'Géodésie nationale',
      'Infrastructure critique',
      'Photogrammétrie UAV',
      'Projets d\'ingénierie de précision',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: true,
  },
  {
    id: 'e-survey-e800',
    name: 'E-SURVEY E800',
    brand: 'E-SURVEY',
    slug: 'e-survey-e800',
    description: 'Récepteur GNSS RTK ultra-compact de la nouvelle génération E-Series.',
    longDescription:
      'Le E-SURVEY E800 marque un tournant dans la miniaturisation des récepteurs GNSS professionnels. Malgré sa compacité, il offre des performances de mesure comparables aux équipements de terrain traditionnel, avec une interface utilisateur intuitive.',
    image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo',
      'Précision RTK': '±10mm + 1ppm (H)',
      'Format': 'Ultra-compact',
      'Autonomie': '8 heures',
      'Protection': 'IP67',
      'Interface': 'Écran tactile couleur',
      'Poids': '0.85 kg',
    },
    applications: [
      'Levés fonciers',
      'Mise à jour cartographique',
      'Inspection d\'infrastructures',
      'Collecte de données terrain',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: false,
  },
  {
    id: 'tk-800',
    name: 'TK-800',
    brand: 'TK',
    slug: 'tk-800',
    description: 'Station totale robotique intelligente pour levés et implantations de précision.',
    longDescription:
      'La TK-800 est une station totale robotique alliant précision angulaire et linéaire exceptionnelles. Sa technologie de suivi automatique de prisme et son interface intuitive permettent un travail en solo efficace sur tous types de chantiers.',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80',
    specifications: {
      'Précision angulaire': '1\" (0.3 mgon)',
      'Précision distance': '±1mm + 1.5ppm (prisme)',
      'Portée sans prisme': '1000 m',
      'Suivi automatique': 'Oui – moteur sans balais',
      'Écran': 'Tactile couleur double face',
      'Mémoire': '32 Go SD',
      'Protection': 'IP55',
      'Autonomie': '6 heures',
    },
    applications: [
      'Implantation de bâtiments',
      'Levés de corps de rue',
      'Contrôle d\'ouvrages d\'art',
      'Auscultation de barrages',
    ],
    category: 'total-stations',
    availableForSale: true,
    availableForRent: true,
    featured: true,
  },
  {
    id: 'south-gnss-s82',
    name: 'SOUTH GNSS S82',
    brand: 'SOUTH',
    slug: 'south-gnss-s82',
    description: 'Récepteur GNSS RTK de référence de SOUTH Surveying & Mapping.',
    longDescription:
      'Le SOUTH GNSS S82 est un récepteur GNSS de nouvelle génération combinant robustesse et haute précision. Sa conception ergonomique et ses capacités multi-constellation en font un choix privilégié pour les bureaux d\'études et géomètres professionnels.',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&q=80',
    specifications: {
      'Constellations': 'GPS, GLONASS, BeiDou, Galileo, QZSS',
      'Canaux': '800 canaux',
      'Précision RTK': '±8mm + 1ppm (H), ±15mm + 1ppm (V)',
      'Communication': '4G LTE / WiFi / Bluetooth',
      'Autonomie': '10 heures',
      'Protection': 'IP67',
      'Température': '-40°C à +65°C',
      'Poids': '1.1 kg',
    },
    applications: [
      'Topographie générale',
      'Ingénierie civile',
      'Cadastre et foncier',
      'Agriculture de précision',
    ],
    category: 'gnss-receivers',
    availableForSale: true,
    availableForRent: true,
    featured: false,
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug)
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured)
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return PRODUCTS.filter((p) => p.category === category)
}
